name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      - name: 📒 Markdown template (with plugins)
        if: ${{ success() || failure() }}
        uses: ZTzTopia/metrics@master
        with:
          template: markdown
          filename: README.md
          markdown: metrics.markdown.template.md
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs 
          plugin_wakatime_user: ZTzTopia
          output_action: pull-request-squash