name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_lines: yes
          output_action: pull-request

      - name: 📒 Markdown template (with plugins)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: README.md
          markdown: metrics.markdown.template.md
          token: ${{ secrets.METRICS_TOKEN }}

      # ======================================================================================
      # 🧩 PLUGINS
      # ======================================================================================

      # ======================================================================================
      # ⚡ Recent activity plugin
      
      - name: ⚡ Recent activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.activity.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_days: 2
          plugin_activity_visibility: no
          plugin_activity_timestamps: yes
  
      # ======================================================================================
      # ⏰ WakaTime plugin

      - name: ⏰ WakaTime
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_user: ZTzTopia
          
       # ======================================================================================
      # 🗳️ Leetcode plugin

      - name: ⏰ Leetcode
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          output_action: pull-request-squash
